var symbols = {
    '/!': "/PrimaryTable/PD.gif"
	, '/#': "/PrimaryTable/Digipeater1.gif"
	, '/$': "/PrimaryTable/Phone.gif"
	, '/%': "/PrimaryTable/DX.gif"
	, '/&': "/PrimaryTable/Gateway.gif"
	, '/\'': "/PrimaryTable/SmallAircraft.gif"
	, '/(': "/PrimaryTable/MobileSatteliteStation.gif"
	, '/)': "/PrimaryTable/Wheelchair.gif"
	, '/*': "/PrimaryTable/SnowMobile.gif"
	, '/+': "/PrimaryTable/RedCross.gif"
	, '/,': "/PrimaryTable/BoyScout.gif"
	, '/-': "/PrimaryTable/House.gif"
	, '/.': "/PrimaryTable/RedX.gif"
	, '//': "/PrimaryTable/RedDot.gif"
	, '/0': "/PrimaryTable/Circle.gif"
	, '/1': "/PrimaryTable/Circle1.gif"
	, '/2': "/PrimaryTable/Circle2.gif"
	, '/3': "/PrimaryTable/Circle3.gif"
	, '/4': "/PrimaryTable/Circle4.gif"
	, '/5': "/PrimaryTable/Circle5.gif"
	, '/6': "/PrimaryTable/Circle6.gif"
	, '/7': "/PrimaryTable/Circle7.gif"
	, '/8': "/PrimaryTable/Circle8.gif"
	, '/9': "/PrimaryTable/Circle9.gif"
	, '/:': "/PrimaryTable/Fire.gif"
	, '/;': "/PrimaryTable/Campground.gif"
	, '/<': "/PrimaryTable/Motorcycle.gif"
	, '/=': "/PrimaryTable/TrainEngine.gif"
	, '/>': "/PrimaryTable/Car.gif"
	, '/?': "/PrimaryTable/FileServer.gif"
	, '/@': "/PrimaryTable/HurricaneFuturePrediction.gif"
	, '/A': "/PrimaryTable/AidStation.gif"
	, '/B': "/PrimaryTable/BullitenSystem.gif"
	, '/C': "/PrimaryTable/Canoe.gif"
	, '/E': "/PrimaryTable/Eye.gif"
	, '/F': "/PrimaryTable/FarmEquipment.gif"
	, '/G': "/PrimaryTable/GridSquare.gif"
	, '/H': "/PrimaryTable/Hotel.gif"
	, '/I': "/PrimaryTable/TCPIPOnAirNetwork.gif"
	, '/K': "/PrimaryTable/School.gif"
	, '/L': "/PrimaryTable/PCUser.gif"
	, '/M': "/PrimaryTable/MacAprs.gif"
	, '/N': "/PrimaryTable/NationalTrafficStation.gif"
	, '/O': "/PrimaryTable/Balloon.gif"
	, '/P': "/PrimaryTable/Police.gif"
	, '/Q': "/PrimaryTable/Quake.gif" // TBD?
	, '/R': "/PrimaryTable/RV.gif"
	, '/S': "/PrimaryTable/Shuttle.gif"
	, '/T': "/PrimaryTable/SSTV.gif"
	, '/U': "/PrimaryTable/Bus.gif"
	, '/V': "/PrimaryTable/ATV.gif"    // TODO: Find out what this really stands for
	, '/W': "/PrimaryTable/NationalWeatherService.gif"
	, '/X': "/PrimaryTable/Helicopter.gif"
	, '/Y': "/PrimaryTable/Yacht.gif"
	, '/Z': "/PrimaryTable/WinAprs.gif"
	, '/[': "/PrimaryTable/Person.gif"
	, '/\\': "/PrimaryTable/DFStation.gif"
	, '/]': "/PrimaryTable/PostOffice.gif"
	, '/^': "/PrimaryTable/LargeAircraft.gif"
	, '/_': "/PrimaryTable/WeatherStation.gif"
	, '/`': "/PrimaryTable/DishAntenna.gif"
	, '/a': "/PrimaryTable/Ambulance.gif"
	, '/b': "/PrimaryTable/Bicycle.gif"
	, '/c': "/PrimaryTable/IncidentCommandPost.gif"
	, '/d': "/PrimaryTable/Firehouse.gif"
	, '/e': "/PrimaryTable/Horse.gif"
	, '/f': "/PrimaryTable/FireTruck.gif"
	, '/g': "/PrimaryTable/Glider.gif"
	, '/h': "/PrimaryTable/Hospital.gif"
	, '/i': "/PrimaryTable/IslandsOnTheAir.gif"
	, '/j': "/PrimaryTable/Jeep.gif"
	, '/k': "/PrimaryTable/Truck.gif"
	, '/l': "/PrimaryTable/Laptop.gif"
	, '/m': "/PrimaryTable/MicERepeater.gif"
	, '/n': "/PrimaryTable/Node.gif"
	, '/o': "/PrimaryTable/EOC.gif"
	, '/p': "/PrimaryTable/Dog.gif"
	, '/q': "/PrimaryTable/GridSquare2.gif"
	, '/r': "/PrimaryTable/Repeater.gif"
	, '/s': "/PrimaryTable/Boat.gif"
	, '/t': "/PrimaryTable/TruckStop.gif"
	, '/u': "/PrimaryTable/SemiTruck.gif"
	, '/v': "/PrimaryTable/Van.gif"
	, '/w': "/PrimaryTable/WaterStation.gif"
	, '/x': "/PrimaryTable/Xastir.gif"
	, '/y': "/PrimaryTable/HouseWithYagi.gif"
	, '/z': "/PrimaryTable/TBD.gif"
	, '/|': "/PrimaryTable/TNCStreamSwitch.gif"
	, '/~': "/PrimaryTable/TNCStreamSwitch1.gif"
	, '\\!': "/AlternateTable/Emergency.gif"
	, '\\#': "/AlternateTable/Digipeater.gif"
	, '\\$': "/AlternateTable/Bank.gif"
        // TODO: Create PowerPlant icon '\\%': "/AlternateTable/.gif"
    , '\\&': "/AlternateTable/BlackDiamond.gif"
	, '\\\'': "/AlternateTable/CrashSite.gif"
	, '\\(': "/AlternateTable/Cloudy.gif"
	, '\\)': "/AlternateTable/Firenet.gif"
	, '\\*': "/AlternateTable/Snow.gif"
	, '\\+': "/AlternateTable/Church.gif"
	, '\\,': "/AlternateTable/GirlScout.gif"
	, '\\-': "/AlternateTable/HouseHF.gif"
	, '\\.': "/AlternateTable/Ambiguous.gif"
	, '\\/': "/AlternateTable/Waypoint.gif"
		// TODO: ADD 802.11 OR OTHER NETWORK NODE ICON (\8)
    , '\\9': "/AlternateTable/GasStation.gif"
	, '\\:': "/AlternateTable/Hail.gif"
	, '\\;': "/AlternateTable/Park.gif"
	, '\\<': "/AlternateTable/WeatherFlag.gif"
		// TODO: ADD APRSTT TOUCHTONE (DTMF USERS) ICON (\=)
    , '\\>': "/AlternateTable/Car.gif"
	, '\\?': "/AlternateTable/InfoKiosk.gif"
	, '\\@': "/AlternateTable/Hurricane.gif"
	, '\\A': "/AlternateTable/OverlayBox.gif"
	, '\\B': "/AlternateTable/BlowingSnow.gif"
	, '\\C': "/AlternateTable/CoastGuard.gif"
	, '\\D': "/AlternateTable/Drizzle.gif"
	, '\\E': "/AlternateTable/Smoke.gif"
	, '\\F': "/AlternateTable/FreezingRain.gif"
	, '\\G': "/AlternateTable/SnowShower.gif"
	, '\\H': "/AlternateTable/Haze.gif"
	, '\\I': "/AlternateTable/RainShower.gif"
	, '\\J': "/AlternateTable/Lightning.gif"
	, '\\K': "/AlternateTable/KenwoodHT.gif"
	, '\\L': "/AlternateTable/Lighthouse.gif"
		// TODO: ADD MARS ICON (\M)
    , '\\N': "/AlternateTable/Bouy.gif"
	, '\\O': "/AlternateTable/Rocket.gif"
	, '\\P': "/AlternateTable/Parking.gif"
	, '\\Q': "/AlternateTable/Earthquake.gif"
	, '\\R': "/AlternateTable/Restaurant.gif"
	, '\\S': "/AlternateTable/Satellite.gif"
	, '\\T': "/AlternateTable/Thunderstorm.gif"
	, '\\U': "/AlternateTable/Sunny.gif"
	, '\\V': "/AlternateTable/VORTAC.gif"
	, '\\W': "/AlternateTable/NWSSite.gif"
	, '\\X': "/AlternateTable/Pharmacy.gif"
		// TODO: ADD RADIOS AND DEVICES ICON (\Y)
    , '\\[': "/AlternateTable/Wallcloud.gif"
		// TODO: ADD OVERLAYABLE GPS SYMBOL (\\)
    , '\\^': "/AlternateTable/Aircraft.gif"
	, '\\_': "/AlternateTable/WXSite.gif"
	, '\\`': "/AlternateTable/Rain.gif"
	, '\\a': "/AlternateTable/ARRL.gif"
	, '\\b': "/AlternateTable/BlowingSand.gif"
	, '\\c': "/AlternateTable/CDTriangle.gif"
	, '\\d': "/AlternateTable/DXSpot.gif"
	, '\\e': "/AlternateTable/Sleet.gif"
	, '\\f': "/AlternateTable/FunnelCloud.gif"
	, '\\g': "/AlternateTable/GaleFlags.gif"
	, '\\h': "/AlternateTable/HamStore.gif"
	, '\\i': "/AlternateTable/POIBox.gif"
	, '\\j': "/AlternateTable/WorkZone.gif"
	, '\\k': "/AlternateTable/SpecialVehicle.gif"
		// TODO: ADD AREAS ICON (\l)
    , '\\m': "/AlternateTable/ValueSign.gif"
	, '\\n': "/AlternateTable/OverlayTriangle.gif"
	, '\\o': "/AlternateTable/SmallCircle.gif"
	, '\\p': "/AlternateTable/PartlyCloudy.gif"
	, '\\r': "/AlternateTable/Restrooms.gif"
	, '\\s': "/AlternateTable/Boat.gif"    // TODO: Make a better graphic
	, '\\t': "/AlternateTable/Tornado.gif"
	, '\\u': "/AlternateTable/Truck.gif"
	, '\\v': "/AlternateTable/Van.gif"
	, '\\w': "/AlternateTable/Flood.gif"
	, '\\x': "/AlternateTable/Obstruction.gif"
	, '\\y': "/AlternateTable/Skywarn.gif"
	, '\\z': "/AlternateTable/Shelter.gif"
	, '\\{': "/AlternateTable/Fog.gif"
	, '\\|': "/AlternateTable/TNCSwitchStream1.gif"
	, '\\~': "/AlternateTable/TNCSwitchStream2.gif"
};

//return "/Crosshair.gif"

function getSymbolPath(symbolTableId, symbolCode) {
    var retVal = symbols[(symbolTableId + symbolCode)];
    
    if(retVal) {
        return retVal;
    } else {
        return "/Crosshair.gif";
    }
}